### ISSUE TITLE
Anti-aliasing

### ISSUE THREAD

**Issue by nikkymen** [florianblume/qt3d-widget#3]
Thanks for the code!

I noticed that your solution does not use anti-aliasing. 

Objects appear smoother when I using Qt3DExtras::Qt3DWindow

Qt3DWidget:
![Qt3DWidget](https://user-images.githubusercontent.com/6241610/105025944-0b206f00-5a5f-11eb-8055-ff63a9c30895.png)

Qt3DWindow:
![Qt3DWindow](https://user-images.githubusercontent.com/6241610/105025902-fe038000-5a5e-11eb-8d19-4cbf4236ae18.png)

Any thoughts on how this can be done?

**Comment by florianblume** [comment]
Hey, thanks for your interest :)

I'm aware of this issue and tried to solve it once already but didn't get it to work. My idea was to use a multisampling texture for offscreen rendering and a second normal texture and use `QBlitFrameBuffer` to get an antialiased image.

If you have an idea feel free to create a pull request :) Maybe I'll get round to checking out this issue the next days.

**Comment by florianblume** [comment]
Could you maybe also share your code? The problem is that in the examples I produced it's not clearly visible whether antialiasing works or not.

**Comment by nikkymen** [comment]
> If you have an idea feel free to create a pull request :) Maybe I'll get round to checking out this issue the next days.

Unfortunately, my experience with OpenGL is almost zero.
I tried to set QSurfaceFormat with setSamples(16) for Qt3DWidget, but this only works for drawing inside Qt3DWidget::paintGL() method

> Could you maybe also share your code? The problem is that in the examples I produced it's not clearly visible whether antialiasing works or not.

Your example is quite suitable for observing this issue: you just need to comment out the animation and replace using Qt3DWidget with Qt3DWindow.

I get the following pictures - the edge differences are quite obvious.

Qt3DWidget:
![widget](https://user-images.githubusercontent.com/6241610/105375655-f50ade00-5c19-11eb-8663-c9f72c4521d4.png)

Qt3DWindow:
![window](https://user-images.githubusercontent.com/6241610/105375680-fa682880-5c19-11eb-8cbc-a8eb3022ea5a.png)

**Comment by florianblume** [comment]
Ah ok well the difference is clearly visible, thanks. I'll try to have another look the next days.

**Comment by florianblume** [comment]
![Screenshot from 2021-01-22 15-18-53](https://user-images.githubusercontent.com/2170192/105501964-2d1b2b00-5cc5-11eb-9a05-5503b65fd4bf.png)

All done ;) You only have to set the version of the format to at least 3.0 and define the number of samples (checkout the README on the main page I'll explain it there).

**Comment by nikkymen** [comment]
> All done ;) You only have to set the version of the format to at least 3.0 and define the number of samples (checkout the README on the main page I'll explain it there).

Nice! I was close to your solution :D
