### ISSUE TITLE
Y-axis is reflected

### ISSUE THREAD

**Issue by nikkymen** [florianblume/qt3d-widget#5]
Hi, after your last changes, there was a problem with the Y-axis - it is reflected.

So I replaced the following shader code:

`"ivec2 tc = ivec2(floor(textureSize(texture) * texc));\n"
`

with

```
"vec2 finalCoord = texc;\n"
"finalCoord.y = 1 - finalCoord.y;\n"
"ivec2 tc = ivec2(floor(textureSize(texture) * finalCoord));\n"
```

Everything works well with this change.

**Comment by florianblume** [comment]
Ah true, thanks for letting me know! I'll implement the changes.
